/*
 * Ranked Choice Voting API
 *
 * This is the API for Creating, Managing and Fetching Polls and Votes for the RCV Project.
 *
 * API version: 1.0.0
 * Contact: test@test.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A PollsApiController binds http requests to an api service and writes the service results to the http response
type PollsApiController struct {
	service PollsApiServicer
}

// NewPollsApiController creates a default api controller
func NewPollsApiController(s PollsApiServicer) Router {
	return &PollsApiController{service: s}
}

// Routes returns all of the api route for the PollsApiController
func (c *PollsApiController) Routes() Routes {
	return Routes{ 
		{
			"CreatePoll",
			strings.ToUpper("Post"),
			"/poll",
			c.CreatePoll,
		},
		{
			"DeletePoll",
			strings.ToUpper("Delete"),
			"/poll/{pollID}",
			c.DeletePoll,
		},
		{
			"GetPoll",
			strings.ToUpper("Get"),
			"/poll/{pollID}",
			c.GetPoll,
		},
		{
			"GetPollResults",
			strings.ToUpper("Get"),
			"/poll/{pollID}/results",
			c.GetPollResults,
		},
		{
			"UpdatePoll",
			strings.ToUpper("Patch"),
			"/poll/{pollID}",
			c.UpdatePoll,
		},
	}
}

// CreatePoll - Creates a new Poll
func (c *PollsApiController) CreatePoll(w http.ResponseWriter, r *http.Request) {
	pollDetails := &PollDetails{}
	if err := json.NewDecoder(r.Body).Decode(&pollDetails); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	result, err := c.service.CreatePoll(r.Context(), *pollDetails)
	// If an error occurred, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// DeletePoll - Deletes an existing Poll
func (c *PollsApiController) DeletePoll(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	pollID, err := parseInt32Parameter(params["pollID"], true)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}

	result, err := c.service.DeletePoll(r.Context(), pollID)
	// If an error occurred, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// GetPoll - Gets a specific Poll by its ID
func (c *PollsApiController) GetPoll(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	pollID, err := parseInt32Parameter(params["pollID"], true)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}

	result, err := c.service.GetPoll(r.Context(), pollID)
	// If an error occurred, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// GetPollResults - Gets the Results of a specific Poll by its ID
func (c *PollsApiController) GetPollResults(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	pollID, err := parseInt32Parameter(params["pollID"], true)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}

	result, err := c.service.GetPollResults(r.Context(), pollID)
	// If an error occurred, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// UpdatePoll - Updates an existing Poll
func (c *PollsApiController) UpdatePoll(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	pollID, err := parseInt32Parameter(params["pollID"], true)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}

	pollDetails := &PollDetails{}
	if err := json.NewDecoder(r.Body).Decode(&pollDetails); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	result, err := c.service.UpdatePoll(r.Context(), pollID, *pollDetails)
	// If an error occurred, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
