/*
 * Ranked Choice Voting API
 *
 * This is the API for Creating, Managing and Fetching Polls and Votes for the RCV Project.
 *
 * API version: 1.0.0-dev
 * Contact: teamsocietyclub@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// VotesApiService is a service that implents the logic for the VotesApiServicer
// This service should implement the business logic for every endpoint for the VotesApi API. 
// Include any external packages or services that will be required by this service.
type VotesApiService struct {
}

// NewVotesApiService creates a default api service
func NewVotesApiService() VotesApiServicer {
	return &VotesApiService{}
}

// PollPollIDVotePost - Cast a vote for a specific Poll
func (s *VotesApiService) PollPollIDVotePost(ctx context.Context, xUSERID string, pollID string, voteInput VoteInput) (ImplResponse, error) {
	// TODO - update PollPollIDVotePost with the required logic for this service method.
	// Add api_votes_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetPollResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetPollResponse{}), nil

	//TODO: Uncomment the next line to return response Response(400, Messages{}) or use other options such as http.Ok ...
	//return Response(400, Messages{}), nil

	//TODO: Uncomment the next line to return response Response(401, Messages{}) or use other options such as http.Ok ...
	//return Response(401, Messages{}), nil

	//TODO: Uncomment the next line to return response Response(403, Messages{}) or use other options such as http.Ok ...
	//return Response(403, Messages{}), nil

	//TODO: Uncomment the next line to return response Response(404, Messages{}) or use other options such as http.Ok ...
	//return Response(404, Messages{}), nil

	//TODO: Uncomment the next line to return response Response(422, Messages{}) or use other options such as http.Ok ...
	//return Response(422, Messages{}), nil

	//TODO: Uncomment the next line to return response Response(500, Messages{}) or use other options such as http.Ok ...
	//return Response(500, Messages{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("PollPollIDVotePost method not implemented")
}

