/*
 * Ranked Choice Voting API
 *
 * This is the API for Creating, Managing and Fetching Polls and Votes for the RCV Project.
 *
 * API version: 1.0.0-dev
 * Contact: teamsocietyclub@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "github.com/google/uuid"

//Response return a ImplResponse struct filled
func Response(code int, body interface{}) ImplResponse {
	return ImplResponse{
		Code: code,
		Body: body,
	}
}

//Message struct appender ??
func AddMessage(messages *Messages, severity Severity, code string, content string) {
	var message Message

	message.Severity = severity
	message.Code = code
	message.MessageContent = content

	if message.Severity == Severity(ERROR) {
		messages.Status = Status(ERROR)
	} else {
		messages.Status = Status(SUCCESSFUL)
	}
	messages.MessageList = append(messages.MessageList, message)
}

func IsValidUUID(u string) bool {
	_, err := uuid.Parse(u)
	return err == nil
}
