/*
 * Ranked Choice Voting API
 *
 * This is the API for Creating, Managing and Fetching Polls and Votes for the RCV Project.
 *
 * API version: 1.0.0-dev
 * Contact: teamsocietyclub@gmail.com
 * Generated by: Can
 */

package openapi

type AddVoteResponse struct {
	Messages Messages `json:"messages,omitempty"`
}
