/*
 * Ranked Choice Voting API
 *
 * This is the API for Creating, Managing and Fetching Polls and Votes for the RCV Project.
 *
 * API version: 1.0.0-dev
 * Contact: teamsocietyclub@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Message - This is a message object for status.
type Message struct {
	Severity Severity `json:"severity"`
	// Alphanumeric code that can be used to identify error and warning messages.
	Code string `json:"code"`
	// End user displayable information which might help diagnose a warning.
	MessageContent string `json:"messageContent"`
}
