/*
 * Ranked Choice Voting API
 *
 * This is the API for Creating, Managing and Fetching Polls and Votes for the RCV Project.
 *
 * API version: 1.0.0
 * Contact: test@test.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Poll struct {

	PollId int64 `json:"pollId,omitempty"`

	RankedChoiceCount int32 `json:"rankedChoiceCount,omitempty"`

	Candidates []Candidate `json:"candidates,omitempty"`
}
