/*
 * Ranked Choice Voting API
 *
 * This is the API for Creating, Managing and Fetching Polls and Votes for the RCV Project.
 *
 * API version: 1.0.0-dev
 * Contact: teamsocietyclub@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// GetPollData - This is the object request information needed to add a poll.
type GetPollData struct {

	// Id for Poll that was created.
	PollId string `json:"pollId,omitempty"`

	// Poll status on being opened for users.
	PollOpen bool `json:"pollOpen,omitempty"`

	// Start date and time for poll to be open. Generated as ISO-0601 that format should be 'yyyy-mm-ddTHH:mm:ss.SSSZ'.
	StartDate time.Time `json:"startDate,omitempty"`

	// End date and time for poll to be open. Generated as ISO-0601 that format should be 'yyyy-mm-ddTHH:mm:ss.SSSZ'.
	EndDate time.Time `json:"endDate,omitempty"`

	// Name for Poll entered by the user used as information purposes only.
	PollName string `json:"pollName,omitempty"`

	// Optional description for Poll entered by the user used as information purposes only.
	PollDesc string `json:"pollDesc,omitempty"`

	MaxNumRankedChoiceCount int32 `json:"maxNumRankedChoiceCount,omitempty"`

	CandidateList []Candidate `json:"candidateList,omitempty"`
}
