/*
 * Ranked Choice Voting API
 *
 * This is the API for Creating, Managing and Fetching Polls and Votes for the RCV Project.
 *
 * API version: 1.0.0-dev
 * Contact: teamsocietyclub@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// UpdatePollRequest - This is the object request information needed to add a poll.
type UpdatePollRequest struct {

	// Poll status on being opened for users.
	PollOpen bool `json:"pollOpen,omitempty"`

	// Name for Poll entered by the user used as information purposes only.
	PollName string `json:"pollName,omitempty"`

	MaxNumRankedChoiceCount int32 `json:"maxNumRankedChoiceCount,omitempty"`

	CandidateList []Candidate `json:"candidateList,omitempty"`
}
