/*
 * Ranked Choice Voting API
 *
 * This is the API for Creating, Managing and Fetching Polls and Votes for the RCV Project.
 *
 * API version: 1.0.0
 * Contact: test@test.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PollDetails struct {

	StartDate string `json:"startDate,omitempty"`

	EndDate string `json:"endDate,omitempty"`

	RankedChoiceCount int32 `json:"rankedChoiceCount,omitempty"`

	Candidates []Candidate `json:"candidates,omitempty"`
}
