server:
  name: societyclub-rcv-backend
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size

# Insert credentials here
credentials: '
'