/*
 * Ranked Choice Voting API
 *
 * This is the API for Creating, Managing and Fetching Polls and Votes for the RCV Project.
 *
 * API version: 1.0.0
 * Contact: test@test.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	PollsApiService := openapi.NewPollsApiService()
	PollsApiController := openapi.NewPollsApiController(PollsApiService)

	VotesApiService := openapi.NewVotesApiService()
	VotesApiController := openapi.NewVotesApiController(VotesApiService)

	router := openapi.NewRouter(PollsApiController, VotesApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
