/*
 * Ranked Choice Voting API
 *
 * This is the API for Creating, Managing and Fetching Polls and Votes for the RCV Project.
 *
 * API version: 1.0.0-dev
 * Contact: teamsocietyclub@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"
	"fmt"

	openapi "github.com/SocietyClub/RCV-backend/go"
)

func main() {
	log.Printf("Server started")
	fmt.Print("Test print")

	PollsApiService := openapi.NewPollsApiService()
	PollsApiController := openapi.NewPollsApiController(PollsApiService)

	VotesApiService := openapi.NewVotesApiService()
	VotesApiController := openapi.NewVotesApiController(VotesApiService)

	router := openapi.NewRouter(PollsApiController, VotesApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
